### ISSUE TITLE
[mock2.0-alpha]express-proxy-middleware error

### ISSUE THREAD

**Issue by whq731** [lincolnlau/swagger-jsblade#3]
```
? 是否需要生成默认配置文件? Yes
[FriJun 16 2017 11:59:38 GMT+0800 (CST)] ERROR 没有找到proxy配置
/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/express-proxy-middleware/index.js:32
        proxyConfig = Object.keys(proxyConfig).map((context) => {
                             ^

TypeError: Cannot convert undefined or null to object
    at getMiddlewareList (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/express-proxy-middleware/index.js:32:30)
    at initialization (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/express-proxy-middleware/index.js:108:22)
    at module.exports (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/express-proxy-middleware/index.js:113:26)
    at /Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/lib/commands/mock.js:159:13
```

----------
mock 2.0 alpha初次试用选择生成配置文件
proxy中间件报错

**Comment by Colafornia** [comment]
fixed
