### ISSUE TITLE
[mock2.0-beta] cb is not a function

### ISSUE THREAD

**Issue by whq731** [lincolnlau/swagger-jsblade#4]
```
? 是否需要生成默认配置文件? Yes
[Thu Jun 22 2017 10:49:14 GMT+0800 (CST)] ERROR 未找到proxy配置
[Thu Jun 22 2017 10:49:14 GMT+0800 (CST)] INFO 未找到proxy配置
The mock server is now running at http://localhost:8000
/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/lib/commands/mock.js:212
        cb(mock.options.file, mock.options.server);
        ^

TypeError: cb is not a function
    at /Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/lib/commands/mock.js:212:9
    at /Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)

```

**Comment by Colafornia** [comment]
fixed in beta.2
