### ISSUE TITLE
[mock2.0-beta]RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by whq731** [lincolnlau/swagger-jsblade#5]
```
? 是否需要生成默认配置文件? Yes
生成默认配置文件成功!文件位置: ./mock.config.js
? 是否以./mock/文件夹初始化swagger文件的mock数据? Yes
RangeError: Maximum call stack size exceeded
    at Array.indexOf (native)
    at Array.indexOf (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/core-js/modules/es6.array.index-of.js:12:17)
    at Object.exports.clone (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/node_modules/hoek/lib/index.js:26:28)
    at Object.exports.clone (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/node_modules/hoek/lib/index.js:76:39)
    at Object.exports.clone (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/node_modules/hoek/lib/index.js:76:39)
    at ObjectParser.generateObject (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/dist/Parsers/ObjectParser.js:44:44)
    at ObjectParser.parse (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/dist/Parsers/ObjectParser.js:38:25)
    at Parser.parse (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/dist/Parser.js:85:41)
    at ArrayParser.generateArray (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/dist/Parsers/ArrayParser.js:49:38)
    at ArrayParser.parse (/Users/weihanqing/.nvm/versions/node/v6.4.0/lib/node_modules/swagger-jsblade/node_modules/swagger-mock-parser/dist/Parsers/ArrayParser.js:34:25)
```

**Comment by whq731** [comment]
![image](https://user-images.githubusercontent.com/5442362/27433460-6634418e-5787-11e7-920f-af346cd4ccb9.png)
可以生成一部分

**Comment by whq731** [comment]
![image](https://user-images.githubusercontent.com/5442362/27433516-b21b32ba-5787-11e7-8e2d-82577481b949.png)
相同path写入config未去重

**Comment by whq731** [comment]
fixd in 0.2.0-beta.3 by MechanicianW
